### ISSUE TITLE
Fix rails 4.0 deprecations

### ISSUE THREAD

**Issue by jimherz** [amerine/acts_as_tree#34]
DEPRECATION WARNING: The following options in your <model_name>.has_many :children declaration are deprecated: :order. Please use a scope block instead. For example, the following:

    has_many :spam_comments, conditions: { spam: true }, class_name: 'Comment'

should be rewritten as the following:

    has_many :spam_comments, -> { where spam: true }, class_name: 'Comment'

DEPRECATION WARNING: Calling #scope or #default_scope with a hash is deprecated. Please use a lambda containing a scope. E.g. scope :red, -> { where(color: 'red') }. (called from acts_as_tree at (eval):3)

**Comment by felixbuenemann** [comment]
Are you using the latest version? This should already be handled properly.

See: https://github.com/amerine/acts_as_tree/blob/master/lib/acts_as_tree.rb#L83

**Comment by jimherz** [comment]
You are correct, thanks!  Sorry, I thought we were on the latest.
