### ISSUE TITLE
Sinatra

### ISSUE THREAD

**Issue by AbdullahMuhammad** [amerine/acts_as_tree#39]
Does acts_as_tree work with Sinatra ?
I am trying to get it working but havent been successful so far.

**Comment by felixbuenemann** [comment]
Try adding `include ActsAsTree` to your ActiveRecord Model.

**Comment by AbdullahMuhammad** [comment]
Yes I did. But didn't work.

**Comment by felixbuenemann** [comment]
You'll have to describe in more detail what you did and what the errors were.

**Comment by felixbuenemann** [comment]
Maybe you could post a short snipped of what you're trying to do as a [gist](https://gist.github.com) and post it here.

**Comment by felixbuenemann** [comment]
@AbdullahMuhammad Have you been able to resolve the problem?

**Comment by felixbuenemann** [comment]
Closing due to lack of feedback.
