### ISSUE TITLE
Method `collection_tree`?

### ISSUE THREAD

**Issue by jmuheim** [amerine/acts_as_tree#49]
The `walk_tree` method is very useful, but sometimes I don't need to walk the collection, I just want to have the collection itself, e.g. to pass it to a select input:

``` slim
= f.association :success_criterion, collection: SuccessCriterion.collection_tree
```

I have created the following method in my `SuccessCriterion` model:

``` ruby
  def self.collection_tree
    success_criteria = []
    walk_tree do |success_criterion, level|
      success_criteria << success_criterion
    end
    success_criteria
  end
```

Maybe something like that exists already and I didn't find it?

**Comment by jmuheim** [comment]
Or is there maybe a way to do this using the default scope?

**Comment by felixbuenemann** [comment]
Currently there is no method that does just that. You can either write your own recursive function (about 3 lines of code). It also possible to get all children in single query using a recursive cte on postgres.

```ruby
# excluding root node
def collect_children(node = self)
   node.children.flat_map { |child| [node] + collect_children(child) }
end
# including root node
def collect_self_and_children(node = self)
  [node] + node.children.flat_map { |child| collect_self_and_children(child) }
end
```

**Comment by jmuheim** [comment]
What speaks agains using the `walk_tree` method and the way I implemented `self.collection_tree`?

**Comment by felixbuenemann** [comment]
Nothing, it's just a bit more verbose.

**Comment by felixbuenemann** [comment]
@jmuheim Can this issue be closed?
