### ISSUE TITLE
2.6's use of `level` clashes with my database column

### ISSUE THREAD

**Issue by matthewrudy** [amerine/acts_as_tree#58]
I was wondering why updating to 2.6 broke my app
then I checked the diff and saw

https://github.com/amerine/acts_as_tree/compare/v2.5.1...v2.6.0

``` diff
+    def level
+      self.ancestors.size
+    end
```

my app already uses `level` to store the depth

``` sql
CREATE TABLE regions (
    id integer NOT NULL,
    name character varying,
    level integer,
    parent_id integer,
);
```

any suggestion for how to avoid this name conflict?

**Comment by matthewrudy** [comment]
For the moment I've tried

``` ruby
  acts_as_tree order: "level"

  # XXX: override acts_as_tree's level method
  def level
    read_attribute(:level)
  end
```

**Comment by felixbuenemann** [comment]
That looks like a valid solution. I've given another solution in #57.

Unfortunately there's not much I can do about it without breaking backwards compatibility. Because the gem is loaded into ActiveRecord::Base the method is defined before the default rails column getter or any other custom method.

**Comment by rainchen** [comment]
@felixbuenemann the `level` method seems too easy to be conflicted, how about considering change it to a new method with a prefix like "tree_level" ?

**Comment by felixbuenemann** [comment]
@rainchen That would be possible, but require a 3.0 release. It's hard to judge from two problem reports wether that change is justified. Maybe @amerine would like to chime in on this?

**Comment by rthbound** [comment]
Suggestion:

Change the method name to `#tree_level` as mentioned by @rainchen, and for compatibility add an alias so that apps can continue using `#level`... Only add that alias if the `#level` method is not yet defined.

**Comment by felixbuenemann** [comment]
`ActsAsTree` is included into `ActiveRecord::Base`, so I think it's not possible to detect wether the method already exists, because it is not defined yet at that point.

**Comment by markhgbrewster** [comment]
I have had a go at solving the issue in this PR: https://github.com/amerine/acts_as_tree/pull/60.
let me know what you think.

**Comment by felixbuenemann** [comment]
@jmuheim Could you test the code from markhgbrewster's PR and test if this also solves your problem reported in issue #57?

You can test it with something like this in your Gemfile:

```ruby
gem "asts_as_tree", github: "markhgbrewster/acts_as_tree", branch: "fix_level_method_name"
```

**Comment by jmuheim** [comment]
@felixbuenemann yes, this fixes my problem.

**Comment by felixbuenemann** [comment]
I have just pushed gem version 2.6.1 which now falls back to the original `#level` method, if it is present in the columns hash. In this case the `#tree_level` method can be used.

Thanks to @markhgbrewster for implementing the fix!
